name: publish-crates-io

on:
  push:
    #tags:
    #  - 'v*'
    branches: [ ci_test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: katyo/publish-crates@v1
        with:
          registroy-token: ${{ secrets.CRATES_IO_TOKEN }}
          path: './sleighcraft'